name: FoliaEssentials
version: '1.0-SNAPSHOT'
main: at.rotesskelett.foliaEssentials.FoliaEssentials
api-version: '1.20.6'
folia-supported: true


commands:
  vanish:
    aliases:
      - v

  foliaessentials:
    aliases:
      - "fles"

  invsee:
    aliases:
      - "inventorysee"

  enderchest:
    aliases:
      - "ec"